language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

addons:
  code_climate:
    repo_token: 1658b8996ad1f56b2760ca808fc6a86ffa0024a1996598c36661227d11a2da8b

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - mocha --require blanket -R mocha-lcov-reporter | codeclimate